-- 관리자 계정 생성
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', 'admin', '관리자', 'admin@kh.com',
			NULL, '010-1111-2222', DEFAULT, DEFAULT, '1',
			NULL, NULL);

-- 회원 삭제
DELETE FROM "MEMBER"
WHERE MEMBER_NO = 2;

CREATE SEQUENCE SEQ_BOARD_CODE NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
CREATE SEQUENCE SEQ_CAREGIVERS_NO NOCACHE;


INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', 'admin', '관리자', 'admin@kh.com',
			NULL, '01011112222', DEFAULT, DEFAULT, 'Y');

-- 회원번호, 아이디, 비번, 이름, 이메일,
-- 주소, 전화번호, 가입일, 탈퇴여부, 관리자계정여부,
-- 요양사 번호, 방번호

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '유저일', 'user01@kh.com',
			NULL, '010-1234-5678', DEFAULT, DEFAULT, DEFAULT,
			NULL, NULL);
	
-- 요양사 추가
INSERT INTO "CAREGIVERS"
VALUES(SEQ_CAREGIVERS_NO.NEXTVAL, '이춘자', 50, 'F', '010-1234-5678', 20, 'MOR');


COMMIT;